config/routes.rb
Rails.application.routes.draw do
  root 'landings#index'

  # Admin dashbaoard routes
  get '/admin', to: 'admin#dashboard', as: 'admin'
  delete '/admin/:id', to: 'admin#destroy', as: :delete

  # Public routes
  get '/:url_id', to: 'url#redirect_user', as: 'redirect'
  get '/s/:url_id', to: 'url#show', as: 'settings'
  post '/', to: 'url#generate', as: 'generate'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  # TODO: IT IS NOT QUIET GOOD!
  validates :url, presence: true,
                  format: { with: /\A(http|https):\/\/(\S+)\z/ }
  validates :url_id, presence: true,
                     uniqueness: { case_sensitive: true }
  validates :status, inclusion: [true, false]
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: ENV.fetch('NAME'), password: ENV.fetch('PASSWORD')

  # Get all URL from database
  def dashboard
    @url = Url.all
  end
  
  # Delete query from database with :delete method
  def destroy

    url = Url.find(params[:id])

    # If it is successful return a success message with flash
    # If not return error message. Sysadmin should check error.
    if url.destroy
      flash[:success] = "Successfully deleted..."
      redirect_to admin_path
    else
      flash[:danger] = "Something went wrong. Please check your logs"
      redirect_to admin_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index; end
end

app/controllers/url_controller.rb
class UrlController < ApplicationController
  def index; end

  def show
    @url = Url.find_by url_id: params[:url_id]

    unless @url
      flash[:danger] = "We didn't find this link. Make sure you have a valid short link."
      render 'landings/index'
    end
  end

  def redirect_user
    @url = Url.find_by url_id: params[:url_id]

    if @url
      @url.update click: @url.click + 1
      redirect_to @url.url
    else
      flash[:danger] = "We didn't find this link. Make sure you have a valid short link."
      render 'landings/index'
    end
  end

  def generate
    @url = Url.new(params.require(:url).permit(:url, :status))
    @url.url_id = generate_id

    if @url.save
      redirect_to settings_path @url.url_id
    else
      flash[:danger] = "Something went wrong. Could you check the link for us?"
      render 'landings/index'
    end
  end

  private

  def generate_id
    alphabet = Array('A'..'Z') + Array('a'..'z')
    numbers = Array(0..9)
    Array.new(6) { (alphabet + numbers).sample }.join
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard.html.erb
<%= provide(:title, 'Dashboard') %>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Original URL</th>
      <th>Generated URL</th>
      <th>Status</th>
      <th>Created</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
  <% @url.each do |url| %>
    <tr>
      <td><%= url.id %></td>
      <td><%= url.url %></td>
      <td><%= url.url_id %></td>
      <td><%= url.status %></td>
      <td><%= url.created_at %></td>
      <td><%= link_to 'Delete', delete_path(url), method: :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/landings/index.html.erb
<%= provide(:title, t('landing.title')) %>

<div style="height: 160px;"></div>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<h1 class="text-center" style="padding-top: 40px;">RedirecTails</h1>

<div class="row">
  <div class="col-lg-6" style="margin: 0 auto;">
    <%= form_for :url, url: generate_path, local: true do |form| %>
      <div class="input-group col-md-12">
        <div class="input-group mb-3">
          <%= form.url_field :url, class: 'form-control', required: true, autofocus: true, placeholder: t('landing.enter_an_url'), 'aria-label': t('landing.enter_an_url'), 'aria-describedby': t('landing.enter_an_url') %>
          <div class="input-group-append">
            <%= form.submit t('landing.generate'), class: 'btn btn-outline-primary', 'aria-label': t('landing.generate'), 'aria-describedby': t('landing.generate')  %>
          </div>
        </div>
      </div>
      <div class="form-check text-right">
        <%= form.check_box :status %> <%= t('landing.is_private') %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="yet-another URL shorter for everyone."/>
    <meta name="author" content="Berkhan Berkdemir"/>

    <title><%= yield :title %> | RedirecTails</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap-reboot.min.css" integrity="sha256-pz64SJ9vnWkyhtOo7mtiOekWuFo7YIGXrzXjElYzcWA=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha256-LA89z+k9fjgMKQ/kq4OO2Mrf8VltYml/VES+Rg0fh20=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'hdata-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        <span class="text-muted">Copyright <%= Time.current.year %>, <a href="https://github.com/BerkhanBerkdemir/redirectails">RedirecTails</a></span>
      </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.1/umd/popper.min.js" integrity="sha256-AoNQZpaRmemSTxMy9xcqXX5VLwI6IMPYugO7bFHOW+U=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha256-5+02zu5UULQkO7w1GIr6vftCgMfFdZcAHeDtFnKZsBs=" crossorigin="anonymous"></script>
  </body>
</html>

app/views/url/show.html.erb
<%= provide(:title, @url.url ) %>
<br>
<p><strong><%= t('show.original_url') %>:</strong> <%= @url.url %> </p>
<p><strong><%= t('show.shortened_link') %>:</strong> <%= link_to @url.url_id, redirect_path %> </p>
<p><strong><%= t('show.clicked') %> :</strong> <%= @url.click %> </p>
<p><strong><%= t('show.status') %>:</strong> <% if @url.status %><%= t('show.private') %><% else %><%= t('show.public') %><% end %> </p>